// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Please follow strict StyleCop, ReSharper, and AI-Refactored code standards for all modifications.
// </auto-generated>

namespace AIRefactored.AI.Navigation
{
    using System;
    using System.Collections.Generic;
    using AIRefactored.Pools;
    using UnityEngine;

    /// <summary>
    /// Quadtree-based spatial index for NavPointData.
    /// Supports fast lookup with optional filtering by zone, elevation, and cover tag.
    /// </summary>
    public sealed class QuadtreeNavGrid
    {
        private const int MaxDepth = 6;
        private const int MaxPointsPerNode = 8;

        private Node _root;

        public QuadtreeNavGrid(Vector2 center, float size)
        {
            float half = size * 0.5f;
            Rect bounds = new Rect(center.x - half, center.y - half, size, size);
            _root = new Node(bounds, 0);
        }

        public void Clear()
        {
            _root = new Node(_root.Bounds, 0);
        }

        public void Insert(NavPointData point)
        {
            if (point == null) return;

            Vector2 pos2D = new Vector2(point.Position.x, point.Position.z);
            Stack<Node> stack = TempStackPool.Rent<Node>();
            stack.Push(_root);

            while (stack.Count > 0)
            {
                Node node = stack.Pop();
                if (!node.Bounds.Contains(pos2D)) continue;

                if (node.IsLeaf)
                {
                    node.NavPoints.Add(point);

                    if (node.NavPoints.Count > MaxPointsPerNode && node.Depth < MaxDepth)
                    {
                        List<NavPointData> tempPoints = node.NavPoints;
                        Subdivide(node);
                        for (int i = 0; i < tempPoints.Count; i++)
                        {
                            Insert(tempPoints[i]); // Re-insert into new tree
                        }
                        TempListPool.Return(tempPoints);
                        node.NavPoints = TempListPool.Rent<NavPointData>();
                    }
                    break;
                }

                for (int i = 0; i < node.Children.Length; i++)
                {
                    stack.Push(node.Children[i]);
                }
            }

            TempStackPool.Return(stack);
        }

        public void Insert(Vector3 point)
        {
            Vector2 pos2D = new Vector2(point.x, point.z);
            Stack<Node> stack = TempStackPool.Rent<Node>();
            stack.Push(_root);

            while (stack.Count > 0)
            {
                Node node = stack.Pop();
                if (!node.Bounds.Contains(pos2D)) continue;

                if (node.IsLeaf)
                {
                    node.RawPoints.Add(point);

                    if (node.RawPoints.Count > MaxPointsPerNode && node.Depth < MaxDepth)
                    {
                        List<Vector3> tempRaw = node.RawPoints;
                        Subdivide(node);
                        for (int i = 0; i < tempRaw.Count; i++)
                        {
                            Insert(tempRaw[i]); // Re-insert
                        }
                        TempListPool.Return(tempRaw);
                        node.RawPoints = TempListPool.Rent<Vector3>();
                    }
                    break;
                }

                for (int i = 0; i < node.Children.Length; i++)
                {
                    stack.Push(node.Children[i]);
                }
            }

            TempStackPool.Return(stack);
        }

        public List<NavPointData> Query(Vector3 position, float radius, Predicate<NavPointData> filter)
        {
            List<NavPointData> result = TempListPool.Rent<NavPointData>();
            float radiusSq = radius * radius;
            Vector2 pos2D = new Vector2(position.x, position.z);
            Rect queryBounds = new Rect(pos2D.x - radius, pos2D.y - radius, radius * 2f, radius * 2f);

            Stack<Node> stack = TempStackPool.Rent<Node>();
            stack.Push(_root);

            while (stack.Count > 0)
            {
                Node node = stack.Pop();
                if (!node.Bounds.Overlaps(queryBounds)) continue;

                if (node.IsLeaf)
                {
                    for (int i = 0; i < node.NavPoints.Count; i++)
                    {
                        NavPointData p = node.NavPoints[i];
                        if ((p.Position - position).sqrMagnitude <= radiusSq && (filter == null || filter(p)))
                        {
                            result.Add(p);
                        }
                    }
                    continue;
                }

                for (int i = 0; i < node.Children.Length; i++)
                {
                    stack.Push(node.Children[i]);
                }
            }

            TempStackPool.Return(stack);
            return result;
        }

        public List<NavPointData> QueryCombined(Vector3 position, float radius, string zone, string elevationBand, string coverTag)
        {
            return Query(position, radius, delegate (NavPointData p)
            {
                if (!string.IsNullOrEmpty(zone) && !string.Equals(p.Zone, zone, StringComparison.OrdinalIgnoreCase)) return false;
                if (!string.IsNullOrEmpty(elevationBand) && !string.Equals(p.ElevationBand, elevationBand, StringComparison.OrdinalIgnoreCase)) return false;
                if (!string.IsNullOrEmpty(coverTag) && !string.Equals(p.Tag, coverTag, StringComparison.OrdinalIgnoreCase)) return false;
                return true;
            });
        }

        public List<Vector3> QueryRaw(Vector3 position, float radius, Predicate<Vector3> filter)
        {
            List<Vector3> result = TempListPool.Rent<Vector3>();
            float radiusSq = radius * radius;
            Vector2 pos2D = new Vector2(position.x, position.z);
            Rect queryBounds = new Rect(pos2D.x - radius, pos2D.y - radius, radius * 2f, radius * 2f);

            Stack<Node> stack = TempStackPool.Rent<Node>();
            stack.Push(_root);

            while (stack.Count > 0)
            {
                Node node = stack.Pop();
                if (!node.Bounds.Overlaps(queryBounds)) continue;

                if (node.IsLeaf)
                {
                    for (int i = 0; i < node.RawPoints.Count; i++)
                    {
                        Vector3 p = node.RawPoints[i];
                        if ((p - position).sqrMagnitude <= radiusSq && (filter == null || filter(p)))
                        {
                            result.Add(p);
                        }
                    }
                    continue;
                }

                for (int i = 0; i < node.Children.Length; i++)
                {
                    stack.Push(node.Children[i]);
                }
            }

            TempStackPool.Return(stack);
            return result;
        }

        private void Subdivide(Node node)
        {
            float halfW = node.Bounds.width * 0.5f;
            float halfH = node.Bounds.height * 0.5f;
            float x = node.Bounds.x;
            float y = node.Bounds.y;
            int d = node.Depth + 1;

            node.Children = new[]
            {
                new Node(new Rect(x, y, halfW, halfH), d),
                new Node(new Rect(x + halfW, y, halfW, halfH), d),
                new Node(new Rect(x, y + halfH, halfW, halfH), d),
                new Node(new Rect(x + halfW, y + halfH, halfW, halfH), d)
            };
        }

        private sealed class Node
        {
            public Node(Rect bounds, int depth)
            {
                this.Bounds = bounds;
                this.Depth = depth;
                this.NavPoints = TempListPool.Rent<NavPointData>();
                this.RawPoints = TempListPool.Rent<Vector3>();
                this.Children = Array.Empty<Node>();
            }

            public Rect Bounds { get; }
            public int Depth { get; }
            public List<NavPointData> NavPoints;
            public List<Vector3> RawPoints;
            public Node[] Children;
            public bool IsLeaf => this.Children.Length == 0;
        }
    }
}
