// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Please follow strict StyleCop, ReSharper, and AI-Refactored code standards for all modifications.
// </auto-generated>

#nullable enable

namespace AIRefactored.AI.Navigation
{
    using System;
    using System.Collections.Generic;
    using EFT.Game.Spawning;
    using UnityEngine;

    /// <summary>
    /// Assigns zone names to world positions using IZones and spawn metadata.
    /// Supports proximity detection, zone weights, and boss presence.
    /// </summary>
    public static class ZoneAssignmentHelper
    {
        private const float BaseBossWeight = 2.5f;
        private const float MaxZoneSnapDistance = 28f;

        private static readonly HashSet<string> _bossZones = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private static readonly Dictionary<string, Vector3> _zoneCenters = new Dictionary<string, Vector3>(StringComparer.OrdinalIgnoreCase);
        private static readonly List<string> _zoneNames = new List<string>(64);
        private static readonly Dictionary<string, List<ISpawnPoint>> _zoneSpawns = new Dictionary<string, List<ISpawnPoint>>(StringComparer.OrdinalIgnoreCase);
        private static readonly Dictionary<string, float> _zoneWeights = new Dictionary<string, float>(StringComparer.OrdinalIgnoreCase);

        private static IZones? _zones;

        /// <summary>
        /// Clears all cached zone data (called on world unload or reset).
        /// </summary>
        public static void Clear()
        {
            _zones = null;
            _zoneCenters.Clear();
            _zoneSpawns.Clear();
            _zoneWeights.Clear();
            _bossZones.Clear();
            _zoneNames.Clear();
        }

        /// <summary>
        /// Returns all known zone names.
        /// </summary>
        public static IReadOnlyList<string> GetAllZoneNames()
        {
            return _zoneNames;
        }

        /// <summary>
        /// Returns the nearest known zone name based on proximity to a position.
        /// </summary>
        public static string GetNearestZone(Vector3 position)
        {
            string best = "unassigned";
            float bestDistSq = MaxZoneSnapDistance * MaxZoneSnapDistance;

            foreach (KeyValuePair<string, Vector3> pair in _zoneCenters)
            {
                float distSq = (pair.Value - position).sqrMagnitude;
                if (distSq < bestDistSq)
                {
                    best = pair.Key;
                    bestDistSq = distSq;
                }
            }

            return best;
        }

        /// <summary>
        /// Gets all spawn points registered under the zone.
        /// </summary>
        public static List<ISpawnPoint> GetSpawnPoints(string zone)
        {
            List<ISpawnPoint>? list;
            if (_zoneSpawns.TryGetValue(zone, out list) && list != null)
            {
                return list;
            }

            return new List<ISpawnPoint>();
        }

        /// <summary>
        /// Returns the average spawn point location for a zone.
        /// </summary>
        public static Vector3 GetZoneCenter(string zone)
        {
            Vector3 pos;
            return _zoneCenters.TryGetValue(zone, out pos) ? pos : Vector3.zero;
        }

        /// <summary>
        /// Returns the tactical weight (risk/value) of a zone.
        /// </summary>
        public static float GetZoneWeight(string zone)
        {
            float value;
            return _zoneWeights.TryGetValue(zone, out value) ? value : 1f;
        }

        /// <summary>
        /// Initializes zone metadata using IZones reference and populates all caches.
        /// </summary>
        /// <param name="zones">IZones instance to scan from.</param>
        /// <param name="includeSnipingZones">Whether to include sniper zones.</param>
        public static void Initialize(IZones zones, bool includeSnipingZones = true)
        {
            if (zones == null)
            {
                throw new ArgumentNullException(nameof(zones));
            }

            _zones = zones;
            _zoneCenters.Clear();
            _zoneSpawns.Clear();
            _zoneWeights.Clear();
            _bossZones.Clear();
            _zoneNames.Clear();

            List<string> zoneList = new List<string>(zones.ZoneNames(includeSnipingZones));

            for (int z = 0; z < zoneList.Count; z++)
            {
                string zoneName = zoneList[z];
                _zoneNames.Add(zoneName);

                ISpawnPoint[] spawns = zones.ZoneSpawnPoints(zoneName);
                if (spawns.Length == 0)
                {
                    continue;
                }

                Vector3 sum = Vector3.zero;
                List<ISpawnPoint> spawnList = new List<ISpawnPoint>(spawns.Length);

                for (int i = 0; i < spawns.Length; i++)
                {
                    ISpawnPoint sp = spawns[i];
                    sum += sp.Position;
                    spawnList.Add(sp);
                }

                _zoneCenters[zoneName] = sum / spawns.Length;
                _zoneSpawns[zoneName] = spawnList;

                float weight = 1f;

                int zoneId;
                if (int.TryParse(zoneName, out zoneId))
                {
                    BotZone botZone = new BotZone { Id = zoneId };
                    Vector3? bossPos = zones.GetBossPosition(botZone);

                    if (bossPos.HasValue)
                    {
                        _bossZones.Add(zoneName);
                        weight += BaseBossWeight;
                    }
                }

                _zoneWeights[zoneName] = weight;
            }
        }

        /// <summary>
        /// Returns true if the specified zone has a known boss presence.
        /// </summary>
        /// <param name="zone">Zone name to check.</param>
        /// <returns>True if boss is present in zone.</returns>
        public static bool IsBossZone(string zone)
        {
            return _bossZones.Contains(zone);
        }
    }
}
