// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Please follow strict StyleCop, ReSharper, and AI-Refactored code standards for all modifications.
// </auto-generated>

#nullable enable

namespace AIRefactored.Runtime
{
    using System;
    using System.Collections.Generic;
    using AIRefactored.AI.Core;
    using AIRefactored.AI.Threads;
    using AIRefactored.Core;
    using BepInEx.Logging;
    using EFT;
    using UnityEngine;

    /// <summary>
    /// Observes new bot spawns and ensures brain injection logic is enforced.
    /// Resets automatically across raids. Skips invalid players and respects GameWorld readiness.
    /// </summary>
    public sealed class BotSpawnListener : MonoBehaviour
    {
        #region Constants

        private const float PollInterval = 1.5f; // Time between bot spawn checks

        #endregion

        #region Fields

        private static readonly HashSet<int> SeenBotIds = new HashSet<int>();
        private static readonly ManualLogSource Logger = AIRefactoredController.Logger;

        private float _nextPollTime = -1f;
        private bool _hasWarnedInvalidState; // To prevent repeating warning messages

        #endregion

        #region Unity Lifecycle

        private void Update()
        {
            // Ensure the game world is initialized and the host is authoritative
            if (!GameWorldHandler.IsInitialized || !GameWorldHandler.IsLocalHost())
            {
                return;
            }

            // Defer scanning until the GameWorld is ready
            if (!GameWorldHandler.IsReady())
            {
                if (!_hasWarnedInvalidState)
                {
                    Logger.LogWarning("[BotSpawnListener] GameWorld not ready — deferring bot scan.");
                    _hasWarnedInvalidState = true;
                }
                return;
            }

            // Resume bot monitoring once GameWorld is ready
            if (_hasWarnedInvalidState)
            {
                Logger.LogInfo("[BotSpawnListener] GameWorld readiness confirmed. Resuming bot monitoring.");
                _hasWarnedInvalidState = false;
            }

            // Only poll at the specified interval to reduce frequency of checks
            float now = Time.time;
            if (now < _nextPollTime)
            {
                return;
            }

            _nextPollTime = now + PollInterval;

            // Get all alive players (bots) — using GameWorldHandler from EFT
            List<Player> players = GameWorldHandler.GetAllAlivePlayers();
            foreach (var player in players)
            {
                // Skip invalid players or non-AI players
                if (player == null || !player.IsAI || player.gameObject == null || player.Profile == null || player.HealthController == null)
                {
                    continue;
                }

                // Avoid processing the same bot multiple times within the same raid
                int id = player.gameObject.GetInstanceID();
                if (!SeenBotIds.Add(id))
                {
                    continue;
                }

                // Ensure bot brain is present or inject if missing
                GameObject botObj = player.gameObject;
                BotBrainGuardian.Enforce(botObj);

                try
                {
                    // Check if the bot already has a BotBrain, if not, inject one
                    if (botObj.GetComponent<BotBrain>() == null)
                    {
                        BotBrain brain = botObj.AddComponent<BotBrain>();
                        BotOwner? botOwner = player.AIData?.BotOwner;
                        if (botOwner != null)
                        {
                            brain.Initialize(botOwner);
                        }

                        string nickname = player.Profile.Info?.Nickname ?? "Unnamed";
                        Logger.LogDebug("[BotSpawnListener] Brain injected for bot: " + nickname);
                    }
                    else
                    {
                        string nickname = player.Profile.Info?.Nickname ?? "Unnamed";
                        Logger.LogDebug("[BotSpawnListener] Brain already present for bot: " + nickname);
                    }
                }
                catch (Exception ex)
                {
                    Logger.LogError("[BotSpawnListener] Failed to inject brain for bot: " + player.Profile?.Info?.Nickname + "\n" + ex.Message);
                }
            }
        }

        private void OnDestroy()
        {
            // Clear the SeenBotIds list and reset states upon destruction (next raid)
            SeenBotIds.Clear();
            Logger.LogInfo("[BotSpawnListener] Destroyed — reset for next raid.");
        }

        #endregion
    }
}
