// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Please follow strict StyleCop, ReSharper, and AI-Refactored code standards for all modifications.
// </auto-generated>

#nullable enable

namespace AIRefactored.Runtime
{
    using System.Collections.Generic;
    using AIRefactored.AI.Core;
    using AIRefactored.AI.Looting;
    using AIRefactored.Core;
    using EFT;
    using EFT.Interactive;
    using UnityEngine;

    /// <summary>
    /// Registers all lootable objects on the map, including containers and loose loot.
    /// Associates loot containers with nearby corpses for AI logic.
    /// Should be executed once per scene during world initialization.
    /// </summary>
    public static class LootBootstrapper
    {
        /// <summary>
        /// Registers all lootable containers and loose items in the scene for AI interaction.
        /// </summary>
        public static void RegisterAllLoot()
        {
            if (!GameWorldHandler.IsInitialized)
            {
                return;
            }

            LootableContainer[] containers = UnityEngine.Object.FindObjectsOfType<LootableContainer>();
            LootItem[] items = UnityEngine.Object.FindObjectsOfType<LootItem>();
            List<Player> players = GameWorldHandler.GetAllAlivePlayers();

            if (containers.Length == 0 && items.Length == 0)
            {
                return;
            }

            if (containers.Length > 0)
            {
                RegisterContainers(containers, players);
            }

            if (items.Length > 0)
            {
                RegisterLooseItems(items);
            }
        }

        private static void RegisterContainers(LootableContainer[] containers, List<Player> players)
        {
            for (int i = 0; i < containers.Length; i++)
            {
                LootableContainer? container = containers[i];
                if (container == null || !container.enabled)
                {
                    continue;
                }

                LootRegistry.RegisterContainer(container);

                if (!FikaHeadlessDetector.IsHeadless)
                {
                    TryRegisterCorpseContainer(container, players);
                }
            }
        }

        private static void RegisterLooseItems(LootItem[] items)
        {
            for (int i = 0; i < items.Length; i++)
            {
                LootItem? item = items[i];
                if (item == null || !item.enabled)
                {
                    continue;
                }

                LootRegistry.RegisterItem(item);
            }
        }

        /// <summary>
        /// Associates a loot container with a dead player if it's nearby or shares transform root.
        /// </summary>
        private static void TryRegisterCorpseContainer(LootableContainer? container, List<Player> players)
        {
            if (container == null || players.Count == 0)
            {
                return;
            }

            Transform? containerTransform = container.transform;
            if (containerTransform == null)
            {
                return;
            }

            Transform? containerRoot = containerTransform.root;
            if (containerRoot == null)
            {
                return;
            }

            Vector3 containerPosition = containerTransform.position;

            for (int i = 0; i < players.Count; i++)
            {
                Player? player = players[i];
                if (player == null || player.HealthController == null || player.HealthController.IsAlive)
                {
                    continue;
                }

                Transform? playerOriginal = player.Transform != null ? player.Transform.Original : null;
                if (playerOriginal == null)
                {
                    continue;
                }

                Transform? playerRoot = playerOriginal.root;
                if (playerRoot == null)
                {
                    continue;
                }

                bool isSameRoot = playerRoot == containerRoot;
                bool isClose = Vector3.Distance(playerOriginal.position, containerPosition) < 1.0f;

                if (isSameRoot || isClose)
                {
                    DeadBodyContainerCache.Register(player, container);
                    break;
                }
            }
        }
    }
}
