// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Please follow strict StyleCop, ReSharper, and AI-Refactored code standards for all modifications.
// </auto-generated>

using MissionType = AIRefactored.AI.Missions.BotMissionController.MissionType;

namespace AIRefactored.AI.Missions.Subsystems
{
    using System;
    using AIRefactored.AI.Core;
    using AIRefactored.AI.Groups;
    using AIRefactored.AI.Helpers;
    using AIRefactored.AI.Looting;
    using AIRefactored.Core;
    using AIRefactored.Runtime;
    using BepInEx.Logging;
    using EFT;
    using UnityEngine;

    /// <summary>
    /// Dynamically switches bot mission type based on panic, aggression, loot opportunity, or squad separation.
    /// </summary>
    public sealed class MissionSwitcher
    {
        #region Constants

        private const float SwitchCooldown = 10f;

        #endregion

        #region Fields

        private readonly BotOwner _bot;
        private readonly BotComponentCache _cache;
        private readonly BotGroupSyncCoordinator _group;
        private readonly BotLootDecisionSystem _lootDecision;
        private readonly BotPersonalityProfile _profile;
        private readonly ManualLogSource _log;

        private float _lastSwitchTime;

        #endregion

        #region Constructor

        public MissionSwitcher(BotOwner bot, BotComponentCache cache)
        {
            if (!EFTPlayerUtil.IsValidBotOwner(bot) || cache == null)
            {
                throw new ArgumentException("[MissionSwitcher] Invalid bot or component cache.");
            }

            _bot = bot;
            _cache = cache;
            _profile = BotRegistry.Get(bot.ProfileId);
            _group = BotCacheUtility.GetGroupSync(cache);
            _lootDecision = cache.LootDecisionSystem;
            _log = Plugin.LoggerInstance;
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Evaluates the bot's current state and switches mission if appropriate.
        /// </summary>
        /// <param name="currentMission">The current mission type of the bot.</param>
        /// <param name="time">Current game time.</param>
        /// <param name="switchToFight">Callback to invoke when switching to Fight.</param>
        /// <param name="resumeQuesting">Callback to invoke when switching to Quest.</param>
        /// <param name="isGroupAligned">Callback to check squad cohesion.</param>
        public void Evaluate(
            ref MissionType currentMission,
            float time,
            Action switchToFight,
            Action resumeQuesting,
            Func<bool> isGroupAligned)
        {
            if (_bot.IsDead || _bot.GetPlayer == null || !_bot.GetPlayer.IsAI)
            {
                return;
            }

            if (time - _lastSwitchTime < SwitchCooldown)
            {
                return;
            }

            string name = _bot.Profile?.Info?.Nickname ?? "Unknown";

            // Escalate to Fight if under fire and aggressive
            if (_bot.Memory != null &&
                _bot.Memory.IsUnderFire &&
                _profile.AggressionLevel > 0.6f &&
                currentMission != MissionType.Fight)
            {
                currentMission = MissionType.Fight;
                _lastSwitchTime = time;
                switchToFight?.Invoke();
                _log.LogDebug("[MissionSwitcher] " + name + " escalating → Fight (under fire + aggressive)");
                return;
            }

            // Opportunistically switch to Loot if mission bias allows it
            if (currentMission == MissionType.Quest &&
                _profile.PreferredMission == MissionBias.Loot &&
                _lootDecision != null &&
                _lootDecision.ShouldLootNow())
            {
                Vector3 lootPos = _lootDecision.GetLootDestination();
                if (lootPos != Vector3.zero)
                {
                    currentMission = MissionType.Loot;
                    _lastSwitchTime = time;
                    _log.LogDebug("[MissionSwitcher] " + name + " switching → Loot (loot opportunity nearby)");
                    return;
                }
            }

            // Fall back to Quest if separated from squad
            if (currentMission == MissionType.Fight && !isGroupAligned())
            {
                currentMission = MissionType.Quest;
                _lastSwitchTime = time;
                resumeQuesting?.Invoke();
                _log.LogDebug("[MissionSwitcher] " + name + " falling back → Quest (squad separation)");
            }
        }

        #endregion
    }
}
