// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Failures in AIRefactored logic must always trigger safe fallback to EFT base AI.
// </auto-generated>

namespace AIRefactored.AI.Movement
{
    using System;
    using AIRefactored.AI.Core;
    using AIRefactored.Core;
    using BepInEx.Logging;
    using EFT;
    using UnityEngine;

    /// <summary>
    /// Controls bot look direction using smooth rotation logic and realistic perception response.
    /// Integrates panic, blindness, sound, and enemy awareness.
    /// All failures are locally isolated; cannot break or cascade into other systems.
    /// </summary>
    public sealed class BotLookController
    {
        #region Constants

        private const float MaxTurnSpeed = 7.5f;
        private const float MinLookDistanceSqr = 0.25f;
        private const float BlindLookRadius = 4f;
        private const float HeardDirectionWeight = 6f;
        private const float SoundMemoryDuration = 4f;

        #endregion

        #region Fields

        private static readonly ManualLogSource Logger = Plugin.LoggerInstance;

        private readonly BotOwner _bot;
        private readonly BotComponentCache _cache;
        private Vector3 _fallbackLookTarget;
        private bool _frozen;

        #endregion

        #region Constructor

        public BotLookController(BotOwner bot, BotComponentCache cache)
        {
            if (!EFTPlayerUtil.IsValidBotOwner(bot) || cache == null)
            {
                Logger.LogError("[BotLookController] Constructor failed — null bot or cache.");
                throw new ArgumentException("Invalid BotLookController parameters.");
            }

            _bot = bot;
            _cache = cache;
            _fallbackLookTarget = bot.Position + bot.LookDirection;
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Updates look direction every tick, enforcing smooth and realistic behavior.
        /// All failures are locally isolated and logged; system cannot break.
        /// </summary>
        public void Tick(float deltaTime)
        {
            try
            {
                if (_frozen || _bot == null || _cache == null || _bot.IsDead || !GameWorldHandler.IsSafeToInitialize)
                {
                    return;
                }

                Player player = EFTPlayerUtil.ResolvePlayer(_bot);
                if (!EFTPlayerUtil.IsValid(player))
                {
                    return;
                }

                Transform body = EFTPlayerUtil.GetTransform(player);
                if (body == null)
                {
                    return;
                }

                Vector3 origin = body.position;
                Vector3 target = ResolveLookTarget(origin);
                Vector3 dir = target - origin;
                dir.y = 0f;

                if (dir.sqrMagnitude < MinLookDistanceSqr)
                {
                    return;
                }

                Quaternion from = body.rotation;
                Quaternion to = Quaternion.LookRotation(dir.normalized);
                body.rotation = Quaternion.Slerp(from, to, Mathf.Clamp01(MaxTurnSpeed * deltaTime));
            }
            catch (Exception ex)
            {
                Logger.LogError("[BotLookController] Tick failed: " + ex);
                try { BotFallbackUtility.FallbackToEFTLogic(_bot); } catch { }
            }
        }

        /// <summary>
        /// Sets a persistent fallback look target.
        /// </summary>
        public void SetLookTarget(Vector3 worldPos)
        {
            try
            {
                if (IsValid(worldPos))
                {
                    _fallbackLookTarget = worldPos;
                }
            }
            catch (Exception ex)
            {
                Logger.LogError("[BotLookController] SetLookTarget failed: " + ex);
            }
        }

        /// <summary>
        /// Freezes look updates.
        /// </summary>
        public void FreezeLook()
        {
            _frozen = true;
        }

        /// <summary>
        /// Resumes look updates.
        /// </summary>
        public void ResumeLook()
        {
            _frozen = false;
        }

        /// <summary>
        /// Gets the bot's current look direction.
        /// </summary>
        public Vector3 GetLookDirection()
        {
            try
            {
                return _bot != null ? _bot.LookDirection : Vector3.forward;
            }
            catch
            {
                return Vector3.forward;
            }
        }

        #endregion

        #region Private Methods

        /// <summary>
        /// Computes the next look target, considering blindness, panic, sound, and enemy threat.
        /// All failures are locally isolated and fallback target is always valid.
        /// </summary>
        private Vector3 ResolveLookTarget(Vector3 origin)
        {
            try
            {
                float now = Time.time;

                // Blind state: look around randomly within a radius.
                if (_cache != null && _cache.IsBlinded && now < _cache.BlindUntilTime)
                {
                    Vector3 offset = UnityEngine.Random.insideUnitSphere;
                    offset.y = 0f;
                    return origin + offset.normalized * BlindLookRadius;
                }

                // Panic state: look toward last heard sound, or fallback.
                if (_cache != null && _cache.Panic != null && _cache.Panic.IsPanicking)
                {
                    if (_cache.HasHeardDirection)
                    {
                        return origin + _cache.LastHeardDirection.normalized * HeardDirectionWeight;
                    }
                    return origin + _bot.LookDirection;
                }

                // Target enemy.
                if (_cache != null && _cache.ThreatSelector != null)
                {
                    string id = _cache.ThreatSelector.GetTargetProfileId();
                    if (!string.IsNullOrEmpty(id))
                    {
                        Player enemy = EFTPlayerUtil.ResolvePlayerById(id);
                        if (EFTPlayerUtil.IsValid(enemy))
                        {
                            Vector3 pos = EFTPlayerUtil.GetPosition(enemy);
                            if (pos.sqrMagnitude > 0.01f)
                            {
                                return pos;
                            }
                        }
                    }
                }

                // Heard sound direction within memory duration.
                if (_cache != null && _cache.HasHeardDirection && now - _cache.LastHeardTime < SoundMemoryDuration)
                {
                    return origin + _cache.LastHeardDirection.normalized * HeardDirectionWeight;
                }

                // Idle scanning: fallback (e.g., previously set patrol/scan direction).
                return _fallbackLookTarget;
            }
            catch (Exception ex)
            {
                Logger.LogError("[BotLookController] ResolveLookTarget failed: " + ex);
                return _fallbackLookTarget;
            }
        }

        private static bool IsValid(Vector3 pos)
        {
            return !float.IsNaN(pos.x) && !float.IsNaN(pos.y) && !float.IsNaN(pos.z);
        }

        #endregion
    }
}
