// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Failures in AIRefactored logic must always trigger safe fallback to EFT base AI.
// </auto-generated>

namespace AIRefactored.AI.Core
{
    using System;
    using AIRefactored.AI.Missions;
    using AIRefactored.Core;
    using AIRefactored.Runtime;
    using BepInEx.Logging;
    using EFT;
    using UnityEngine;

    /// <summary>
    /// Holds AIRefactored-specific metadata for a bot, including personality, zone, tuning, and runtime behavior state.
    /// Always yields to vanilla logic if any core field is invalid. Never disables the owner.
    /// Bulletproof: all failures are isolated, never cascade.
    /// </summary>
    public sealed class AIRefactoredBotOwner
    {
        #region Static

        private static readonly ManualLogSource Logger = Plugin.LoggerInstance;

        #endregion

        #region Fields

        private BotOwner _bot;
        private BotComponentCache _cache;
        private BotMissionController _missionController;
        private bool _isInitialized;
        private bool _isFallback;

        #endregion

        #region Properties

        public BotOwner Bot
        {
            get
            {
                if (!_isInitialized || _bot == null || _isFallback)
                {
                    TriggerTerminalFallback("[AIRefactoredBotOwner] Bot accessed before initialization or after fallback.");
                    return null;
                }
                return _bot;
            }
        }

        public BotComponentCache Cache
        {
            get
            {
                if (!_isInitialized || _cache == null || _isFallback)
                {
                    TriggerTerminalFallback("[AIRefactoredBotOwner] Cache accessed before initialization or after fallback.");
                    return BotComponentCache.Empty;
                }
                return _cache;
            }
        }

        public BotMissionController MissionController
        {
            get
            {
                if (_missionController == null || _isFallback)
                {
                    TriggerTerminalFallback("[AIRefactoredBotOwner] MissionController is null or in fallback.");
                }
                return _missionController;
            }
        }

        public BotPersonalityProfile PersonalityProfile { get; private set; }
        public string PersonalityName { get; private set; }
        public string AssignedZone { get; private set; }

        #endregion

        #region Constructor

        public AIRefactoredBotOwner()
        {
            PersonalityProfile = new BotPersonalityProfile();
            PersonalityName = "Unknown";
            AssignedZone = "unknown";
        }

        #endregion

        #region Initialization

        /// <summary>
        /// Initializes the owner and sets up cache and personality.
        /// </summary>
        /// <param name="bot">BotOwner instance.</param>
        public void Initialize(BotOwner bot)
        {
            if (_isFallback)
                return;

            if (bot == null)
            {
                TriggerTerminalFallback("[AIRefactoredBotOwner] Initialization failed: bot is null.");
                _isInitialized = false;
                return;
            }
            if (_isInitialized)
                return;

            _bot = bot;
            try
            {
                _cache = BotComponentCacheRegistry.GetOrCreate(bot);
                _cache.SetOwner(this);

                string profileId = bot.Profile?.Id ?? "null-profile";
                WildSpawnType role = bot.Profile?.Info?.Settings?.Role ?? WildSpawnType.assault;
                BotPersonalityProfile profile = BotRegistry.GetOrGenerate(profileId, PersonalityType.Balanced, role);

                InitProfile(profile, profile?.Personality.ToString() ?? "Balanced");
                _isInitialized = true;

                if (!FikaHeadlessDetector.IsHeadless)
                {
                    string nickname = bot.Profile?.Info?.Nickname ?? "Unnamed";
                    Logger.LogDebug($"[AIRefactoredBotOwner] Initialized for bot: {nickname}");
                }
            }
            catch (Exception ex)
            {
                TriggerTerminalFallback($"[AIRefactoredBotOwner] Initialization failed: {ex}");
                _isInitialized = false;
            }
        }

        #endregion

        #region Personality

        /// <summary>
        /// Initializes from a preset PersonalityType.
        /// </summary>
        public void InitProfile(PersonalityType type)
        {
            if (_isFallback)
                return;

            try
            {
                if (!BotPersonalityPresets.Presets.TryGetValue(type, out var preset) || preset == null)
                {
                    preset = BotPersonalityPresets.Presets[PersonalityType.Adaptive];
                    PersonalityName = "Adaptive";
                    Logger.LogWarning($"[AIRefactoredBotOwner] Invalid personality type '{type}' — using Adaptive.");
                }
                else
                {
                    PersonalityName = type.ToString();
                }
                PersonalityProfile = preset;

                if (!FikaHeadlessDetector.IsHeadless)
                {
                    Logger.LogDebug($"[AIRefactoredBotOwner] Personality assigned: {PersonalityName}");
                }
            }
            catch (Exception ex)
            {
                TriggerTerminalFallback($"[AIRefactoredBotOwner] InitProfile failed: {ex}");
                PersonalityProfile = new BotPersonalityProfile();
                PersonalityName = "Default";
            }
        }

        /// <summary>
        /// Initializes from a custom profile and name.
        /// </summary>
        public void InitProfile(BotPersonalityProfile profile, string name)
        {
            if (_isFallback)
                return;

            try
            {
                if (profile == null)
                {
                    TriggerTerminalFallback("[AIRefactoredBotOwner] InitProfile failed: profile is null.");
                    PersonalityProfile = new BotPersonalityProfile();
                    PersonalityName = "Default";
                    return;
                }
                PersonalityProfile = profile;
                PersonalityName = string.IsNullOrEmpty(name) ? "Custom" : name;

                if (!FikaHeadlessDetector.IsHeadless)
                {
                    Logger.LogDebug($"[AIRefactoredBotOwner] Custom profile assigned: {PersonalityName}");
                }
            }
            catch (Exception ex)
            {
                TriggerTerminalFallback($"[AIRefactoredBotOwner] Exception in InitProfile(profile,name): {ex}");
                PersonalityProfile = new BotPersonalityProfile();
                PersonalityName = "Default";
            }
        }

        /// <summary>
        /// Clears the personality to a default state.
        /// </summary>
        public void ClearPersonality()
        {
            if (_isFallback)
                return;

            try
            {
                PersonalityProfile = new BotPersonalityProfile();
                PersonalityName = "Cleared";

                if (!FikaHeadlessDetector.IsHeadless)
                {
                    Logger.LogDebug("[AIRefactoredBotOwner] Personality cleared.");
                }
            }
            catch
            {
                // Silent fail
            }
        }

        /// <summary>
        /// Returns true if personality is assigned.
        /// </summary>
        public bool HasPersonality()
        {
            return !_isFallback && PersonalityProfile != null;
        }

        #endregion

        #region Zone + Mission

        /// <summary>
        /// Sets the assigned zone name for this bot.
        /// </summary>
        public void SetZone(string zoneName)
        {
            if (_isFallback)
                return;

            try
            {
                if (string.IsNullOrEmpty(zoneName))
                    return;

                AssignedZone = zoneName;

                if (!FikaHeadlessDetector.IsHeadless)
                {
                    Logger.LogDebug($"[AIRefactoredBotOwner] Zone assigned: {zoneName}");
                }
            }
            catch (Exception ex)
            {
                Logger.LogError($"[AIRefactoredBotOwner] Exception in SetZone: {ex}");
            }
        }

        /// <summary>
        /// Sets the mission controller.
        /// </summary>
        public void SetMissionController(BotMissionController controller)
        {
            if (_isFallback)
                return;

            try
            {
                if (controller == null)
                {
                    TriggerTerminalFallback("[AIRefactoredBotOwner] SetMissionController failed: controller is null.");
                    return;
                }
                _missionController = controller;
            }
            catch (Exception ex)
            {
                TriggerTerminalFallback($"[AIRefactoredBotOwner] Exception in SetMissionController: {ex}");
            }
        }

        #endregion

        #region Fallback Utility

        /// <summary>
        /// Triggers terminal fallback on this owner. This is one-shot and permanent.
        /// </summary>
        private void TriggerTerminalFallback(string logMsg)
        {
            if (_isFallback)
                return;

            _isFallback = true;
            if (!string.IsNullOrEmpty(_bot?.Profile?.Id))
                BotRegistry.MarkFallback(_bot.Profile.Id);

            if (!FikaHeadlessDetector.IsHeadless)
                Logger.LogError(logMsg);

            BotFallbackUtility.FallbackToEFTLogic(_bot);
        }

        #endregion
    }
}
