// <auto-generated>
//   AI-Refactored: BotComponentCacheRegistry.cs (Beyond Diamond – Ultimate Safety & Extensibility, June 2025)
//   Atomic, thread-safe, no duplicate/invalid wiring, bulletproof profile/player cache logic.
//   Unified headless/client attach, idempotent, error-contained. MIT License.
// </auto-generated>

namespace AIRefactored.AI.Core
{
    using System;
    using System.Collections.Generic;
    using AIRefactored.Core;
    using AIRefactored.Runtime;
    using BepInEx.Logging;
    using EFT;

    /// <summary>
    /// Central static registry for storing and accessing BotComponentCache instances.
    /// All wiring is atomic, fully thread-safe, idempotent, and null-guarded.
    /// Caches are keyed by ProfileId and Player instance, always retry-attached and error-contained.
    /// </summary>
    public static class BotComponentCacheRegistry
    {
        #region Internal State

        private static readonly Dictionary<string, BotComponentCache> CacheMap =
            new Dictionary<string, BotComponentCache>(128, StringComparer.OrdinalIgnoreCase);

        private static readonly Dictionary<Player, BotComponentCache> PlayerMap =
            new Dictionary<Player, BotComponentCache>(128);

        private static readonly object Lock = new object();
        private static readonly ManualLogSource Logger = Plugin.LoggerInstance;

        #endregion

        #region Public API

        /// <summary>
        /// Returns or creates the cache for a bot. 
        /// Always wires cache and owner; idempotent and never disables on error.
        /// </summary>
        public static BotComponentCache GetOrCreate(BotOwner bot)
        {
            if (!IsFullyValidBot(bot))
                return null;

            string id = bot.Profile.Id;
            Player player = bot.GetPlayer;
            if (string.IsNullOrEmpty(id) || player == null || bot.AIData == null)
                return null;

            lock (Lock)
            {
                if (CacheMap.TryGetValue(id, out var existing))
                {
                    if (!PlayerMap.ContainsKey(player))
                        PlayerMap[player] = existing;
                    return existing;
                }

                try
                {
                    var cache = new BotComponentCache();
                    cache.Initialize(bot);

                    var owner = new AIRefactoredBotOwner();
                    cache.SetOwner(owner);
                    owner.Initialize(bot);

                    CacheMap[id] = cache;
                    PlayerMap[player] = cache;

                    Logger.LogDebug($"[BotComponentCacheRegistry] Created and initialized new cache for bot: {id}");
                    return cache;
                }
                catch (Exception ex)
                {
                    Logger.LogError($"[BotComponentCacheRegistry] Cache creation failed for {id}: {ex}");
                    return null;
                }
            }
        }

        /// <summary>
        /// Attempts to retrieve an existing cache for a BotOwner.
        /// </summary>
        public static BotComponentCache TryGetExisting(BotOwner bot)
        {
            if (!IsFullyValidBot(bot))
                return null;

            string id = bot.Profile.Id;
            lock (Lock)
            {
                return CacheMap.TryGetValue(id, out var existing) ? existing : null;
            }
        }

        /// <summary>
        /// Tries to get a cache by ProfileId.
        /// </summary>
        public static bool TryGet(string profileId, out BotComponentCache cache)
        {
            cache = null;
            if (string.IsNullOrEmpty(profileId))
                return false;

            lock (Lock)
            {
                return CacheMap.TryGetValue(profileId, out cache);
            }
        }

        /// <summary>
        /// Tries to get a cache by Player.
        /// </summary>
        public static bool TryGetByPlayer(Player player, out BotComponentCache cache)
        {
            cache = null;
            if (player == null)
                return false;

            lock (Lock)
            {
                if (PlayerMap.TryGetValue(player, out cache))
                    return true;

                string id = player.Profile?.Id;
                if (!string.IsNullOrEmpty(id) && CacheMap.TryGetValue(id, out cache))
                {
                    PlayerMap[player] = cache;
                    return true;
                }

                return false;
            }
        }

        /// <summary>
        /// Tries to get a cache by BotOwner.
        /// </summary>
        public static bool TryGetByBotOwner(BotOwner bot, out BotComponentCache cache)
        {
            cache = null;
            if (!IsFullyValidBot(bot))
                return false;

            return TryGet(bot.Profile.Id, out cache);
        }

        /// <summary>
        /// Removes a bot's cache from both ProfileId and Player maps.
        /// Idempotent and never throws.
        /// </summary>
        public static void Remove(BotOwner bot)
        {
            if (bot?.Profile?.Id == null)
                return;

            string id = bot.Profile.Id;
            Player player = bot.GetPlayer;

            lock (Lock)
            {
                CacheMap.Remove(id);
                if (player != null)
                    PlayerMap.Remove(player);

                Logger.LogDebug($"[BotComponentCacheRegistry] Removed cache for: {id}");
            }
        }

        /// <summary>
        /// Removes all bot caches (used during full raid shutdown).
        /// Safe for multi-raid, always zeroes both maps.
        /// </summary>
        public static void ClearAll()
        {
            lock (Lock)
            {
                CacheMap.Clear();
                PlayerMap.Clear();
                Logger.LogWarning("[BotComponentCacheRegistry] All caches cleared.");
            }
        }

        #endregion

        #region Utility

        /// <summary>
        /// Checks if a BotOwner is fully valid for registry use.
        /// </summary>
        private static bool IsFullyValidBot(BotOwner bot)
        {
            return bot != null &&
                   bot.Profile != null &&
                   bot.Profile.Info != null &&
                   !string.IsNullOrEmpty(bot.Profile.Id) &&
                   bot.GetPlayer != null &&
                   bot.AIData != null;
        }

        #endregion
    }
}
