// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Please follow strict StyleCop, ReSharper, and AI-Refactored code standards for all modifications.
// </auto-generated>

#nullable enable

namespace AIRefactored.AI.Hotspots
{
    using System;
    using System.Collections.Generic;
    using AIRefactored.Runtime;
    using BepInEx.Logging;
    using UnityEngine;

    /// <summary>
    /// Global registry for map-specific hotspots (loot zones, patrol targets, tactical nodes).
    /// Dynamically builds spatial indexes (quadtree or grid) depending on map type.
    /// </summary>
    public static class HotspotRegistry
    {
        private static readonly List<Hotspot> All = new List<Hotspot>(256);
        private static readonly Dictionary<string, List<Hotspot>> ByZone = new Dictionary<string, List<Hotspot>>(StringComparer.OrdinalIgnoreCase);

        private static readonly Dictionary<string, SpatialIndexMode> IndexModeMap = new Dictionary<string, SpatialIndexMode>(StringComparer.OrdinalIgnoreCase)
        {
            { "woods", SpatialIndexMode.Quadtree },
            { "shoreline", SpatialIndexMode.Quadtree },
            { "lighthouse", SpatialIndexMode.Quadtree },
            { "interchange", SpatialIndexMode.Quadtree },
            { "bigmap", SpatialIndexMode.Quadtree },
            { "sandbox", SpatialIndexMode.Grid },
            { "sandbox_high", SpatialIndexMode.Grid },
            { "factory4_day", SpatialIndexMode.Grid },
            { "factory4_night", SpatialIndexMode.Grid },
            { "laboratory", SpatialIndexMode.Grid },
            { "tarkovstreets", SpatialIndexMode.Grid },
            { "rezervbase", SpatialIndexMode.Grid }
        };

        private static readonly ManualLogSource Logger = AIRefactoredController.Logger;

        private static SpatialIndexMode _activeMode = SpatialIndexMode.None;
        private static string _loadedMap = "none";
        private static HotspotQuadtree? _quadtree;
        private static HotspotSpatialGrid? _grid;
        private static bool _initialized;

        private enum SpatialIndexMode
        {
            None,
            Quadtree,
            Grid
        }

        public static void Clear()
        {
            All.Clear();
            ByZone.Clear();
            _quadtree = null;
            _grid = null;
            _loadedMap = "none";
            _activeMode = SpatialIndexMode.None;
            _initialized = false;
        }

        public static IReadOnlyList<Hotspot> GetAll() => All;

        public static IReadOnlyList<Hotspot> GetAllInZone(string zone)
        {
            return ByZone.TryGetValue(zone, out List<Hotspot>? result)
                ? result
                : Array.Empty<Hotspot>();
        }

        public static Hotspot GetRandomHotspot()
        {
            return All.Count == 0
                ? new Hotspot(Vector3.zero, "none")
                : All[UnityEngine.Random.Range(0, All.Count)];
        }

        public static void Initialize(string mapId)
        {
            if (_initialized || string.IsNullOrEmpty(mapId) || _loadedMap.Equals(mapId, StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            Clear();

            _initialized = true;
            _loadedMap = mapId.ToLowerInvariant();
            _activeMode = IndexModeMap.TryGetValue(_loadedMap, out SpatialIndexMode mode) ? mode : SpatialIndexMode.None;

            HotspotSet? set = HardcodedHotspots.GetForMap(_loadedMap);
            if (set?.Points == null)
            {
                Logger.LogWarning($"[HotspotRegistry] ⚠ No hotspot set or point list found for map '{_loadedMap}'");
                return;
            }

            foreach (var point in set.Points)
            {
                if (point == null || string.IsNullOrWhiteSpace(point.Zone))
                {
                    continue;
                }

                var hotspot = new Hotspot(point.Position, point.Zone);
                All.Add(hotspot);

                if (!ByZone.TryGetValue(point.Zone, out List<Hotspot>? zoneList))
                {
                    zoneList = new List<Hotspot>(8);
                    ByZone[point.Zone] = zoneList;
                }

                zoneList.Add(hotspot);
            }

            switch (_activeMode)
            {
                case SpatialIndexMode.Quadtree:
                    BuildQuadtree();
                    break;
                case SpatialIndexMode.Grid:
                    BuildGrid();
                    break;
            }

            Logger.LogInfo($"[HotspotRegistry] ✅ Registered {All.Count} hotspots for map '{_loadedMap}' using {_activeMode}");
        }

        public static List<Hotspot> QueryNearby(Vector3 position, float radius, Predicate<Hotspot>? filter = null)
        {
            if (_activeMode == SpatialIndexMode.Quadtree && _quadtree != null)
            {
                return _quadtree.Query(position, radius, filter);
            }

            if (_activeMode == SpatialIndexMode.Grid && _grid != null)
            {
                return _grid.Query(position, radius, filter);
            }

            return FallbackQuery(position, radius, filter);
        }

        private static void BuildGrid()
        {
            _grid = new HotspotSpatialGrid(10.0f);
            foreach (var hotspot in All)
            {
                _grid.Insert(hotspot);
            }
        }

        private static void BuildQuadtree()
        {
            Vector2 center = EstimateCenter();
            float size = EstimateBoundsSize(center);
            _quadtree = new HotspotQuadtree(center, size);

            foreach (var hotspot in All)
            {
                _quadtree.Insert(hotspot);
            }
        }

        private static float EstimateBoundsSize(Vector2 center)
        {
            float max = 0.0f;
            for (int i = 0; i < All.Count; i++)
            {
                Vector3 p = All[i].Position;
                float dist = Vector2.Distance(new Vector2(p.x, p.z), center);
                if (dist > max)
                {
                    max = dist;
                }
            }

            return Mathf.NextPowerOfTwo(Mathf.CeilToInt(max * 2.0f));
        }

        private static Vector2 EstimateCenter()
        {
            float minX = float.MaxValue;
            float maxX = float.MinValue;
            float minZ = float.MaxValue;
            float maxZ = float.MinValue;

            for (int i = 0; i < All.Count; i++)
            {
                Vector3 p = All[i].Position;
                if (p.x < minX) minX = p.x;
                if (p.x > maxX) maxX = p.x;
                if (p.z < minZ) minZ = p.z;
                if (p.z > maxZ) maxZ = p.z;
            }

            return new Vector2((minX + maxX) * 0.5f, (minZ + maxZ) * 0.5f);
        }

        private static List<Hotspot> FallbackQuery(Vector3 position, float radius, Predicate<Hotspot>? filter)
        {
            List<Hotspot> result = new List<Hotspot>(16);
            float radiusSqr = radius * radius;

            for (int i = 0; i < All.Count; i++)
            {
                Hotspot h = All[i];
                if ((h.Position - position).sqrMagnitude <= radiusSqr &&
                    (filter == null || filter(h)))
                {
                    result.Add(h);
                }
            }

            return result;
        }

        /// <summary>
        /// Represents a single registered hotspot with position and zone.
        /// </summary>
        public sealed class Hotspot
        {
            public Hotspot(Vector3 pos, string zone)
            {
                this.Position = pos;
                this.Zone = zone;
            }

            public Vector3 Position { get; }

            public string Zone { get; }
        }
    }
}
