// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Please follow strict StyleCop, ReSharper, and AI-Refactored code standards for all modifications.
// </auto-generated>

namespace AIRefactored.AI
{
    using System;

    /// <summary>
    /// Defines a full personality configuration for AI bots, including behavior flags,
    /// tactical parameters, suppression response, and mission preferences.
    /// </summary>
    public sealed class BotPersonalityProfile
    {
        #region Personality Parameters

        public float Accuracy;
        public float AccuracyUnderFire;
        public float AggressionLevel;
        public float Caution;
        public float ChaosFactor;
        public float Cohesion;
        public float CommunicationLevel;
        public float CornerCheckPauseTime;
        public float EngagementRange;
        public float FlankBias;
        public float FlinchThreshold;
        public float LeanPeekFrequency;
        public float MovementJitter;
        public float ReactionSpeed;
        public float ReactionTime;
        public float RepositionPriority;
        public float RetreatThreshold;
        public float RiskTolerance;
        public float SideStepBias;
        public float SuppressionSensitivity;
        public float SuppressiveFireBias;
        public float Greed;
        public float StuckTolerance;

        #endregion

        #region Behavior Flags

        public bool IsCamper;
        public bool IsDumb;
        public bool IsFearful;
        public bool IsFrenzied;
        public bool IsSadistic;
        public bool IsSilentHunter;
        public bool IsStubborn;
        public bool IsTeamPlayer;

        #endregion

        #region Identity

        public PersonalityType Personality;
        public MissionBias PreferredMission;
        public LeanPreference LeaningStyle;

        #endregion

        #region Derived Properties

        public bool CanFlank
        {
            get { return this.FlankBias > 0.05f; }
        }

        public bool CanRetreat
        {
            get { return this.RetreatThreshold > 0.05f; }
        }

        public bool CanSuppress
        {
            get { return this.SuppressiveFireBias > 0.05f; }
        }

        #endregion

        #region Methods

        /// <summary>
        /// Returns a shallow copy of this profile for runtime modification.
        /// </summary>
        /// <returns>Shallow clone of <see cref="BotPersonalityProfile"/>.</returns>
        public BotPersonalityProfile Clone()
        {
            return (BotPersonalityProfile)this.MemberwiseClone();
        }

        /// <summary>
        /// Debug-friendly representation for profile introspection.
        /// </summary>
        /// <returns>Profile debug string.</returns>
        public override string ToString()
        {
            return "[" + this.Personality + "] Aggro=" + this.AggressionLevel + ", Acc=" + this.Accuracy + ", Chaos=" + this.ChaosFactor + ", Cohesion=" + this.Cohesion;
        }

        #endregion
    }

    #region Enums

    /// <summary>
    /// Canonical list of supported personality archetypes.
    /// </summary>
    public enum PersonalityType
    {
        Adaptive,
        Aggressive,
        Balanced,
        Camper,
        Cautious,
        ColdBlooded,
        Defensive,
        Dumb,
        Explorer,
        Fearful,
        Frenzied,
        Greedy,
        Heroic,
        Loner,
        Methodical,
        Paranoid,
        Patient,
        Reckless,
        RiskTaker,
        SilentHunter,
        Sniper,
        Strategic,
        Stubborn,
        Tactical,
        TeamPlayer,
        Unpredictable,
        Vengeful,
        Vigilant,
        Calculating,
        Panicked,
        Stoic,
        Bulldozer,
        Covert,
        Cowardly,
        Disruptor,
        Supportive,
        Hunter,
        Stalker,
        Vigilante,
        Sentinel,
        Erratic,
        Cowboy,
        Saboteur
    }

    /// <summary>
    /// Mission-type inclination to bias looting vs fighting vs questing.
    /// </summary>
    public enum MissionBias
    {
        Random,
        Loot,
        Fight,
        Quest
    }

    /// <summary>
    /// Determines lean style for tactical positioning.
    /// </summary>
    public enum LeanPreference
    {
        Never,
        Conservative,
        Aggressive
    }

    #endregion
}
