// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   All registry logic is bulletproof: always atomically wires owner+cache, always retries, never leaves bots unwired.
// </auto-generated>

namespace AIRefactored
{
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using AIRefactored.AI;
    using AIRefactored.AI.Core;
    using AIRefactored.Core;
    using AIRefactored.Runtime;
    using BepInEx.Logging;
    using EFT;

    /// <summary>
    /// Global personality and owner registry for AI-Refactored bots.
    /// Boot-safe, null-safe, allocation-resistant, and guarantees atomic owner/cache wiring. Never blocks or leaves bots unwired.
    /// </summary>
    public static class BotRegistry
    {
        #region Fields

        private static readonly ConcurrentDictionary<string, BotPersonalityProfile> _profileRegistry = new ConcurrentDictionary<string, BotPersonalityProfile>();
        private static readonly ConcurrentDictionary<string, AIRefactoredBotOwner> _ownerRegistry = new ConcurrentDictionary<string, AIRefactoredBotOwner>();
        private static readonly Dictionary<PersonalityType, BotPersonalityProfile> _fallbackProfiles = new Dictionary<PersonalityType, BotPersonalityProfile>();
        private static readonly HashSet<string> _missingLogged = new HashSet<string>();

        private static readonly Dictionary<WildSpawnType, PersonalityType> _roleMap = new Dictionary<WildSpawnType, PersonalityType>
        {
            { WildSpawnType.assault, PersonalityType.Aggressive },
            { WildSpawnType.marksman, PersonalityType.Sniper },
            { WildSpawnType.pmcUSEC, PersonalityType.Strategic },
            { WildSpawnType.pmcBEAR, PersonalityType.Strategic },
            { WildSpawnType.exUsec, PersonalityType.Methodical },
            { WildSpawnType.crazyAssaultEvent, PersonalityType.Erratic },
            { WildSpawnType.bossBully, PersonalityType.Bulldozer },
            { WildSpawnType.followerBully, PersonalityType.Bulldozer },
            { WildSpawnType.bossTagilla, PersonalityType.Bulldozer },
            { WildSpawnType.bossGluhar, PersonalityType.Sentinel },
            { WildSpawnType.followerGluharAssault, PersonalityType.Sentinel },
            { WildSpawnType.followerGluharSecurity, PersonalityType.Sentinel },
            { WildSpawnType.followerGluharScout, PersonalityType.Strategic },
            { WildSpawnType.bossKilla, PersonalityType.Frenzied },
            { WildSpawnType.bossKnight, PersonalityType.Cowboy },
            { WildSpawnType.followerBigPipe, PersonalityType.Hunter },
            { WildSpawnType.followerBirdEye, PersonalityType.Sniper },
            { WildSpawnType.sectantPriest, PersonalityType.Cautious },
            { WildSpawnType.sectantWarrior, PersonalityType.Disruptor },
            { WildSpawnType.bossSanitar, PersonalityType.Supportive },
            { WildSpawnType.followerSanitar, PersonalityType.Supportive },
            { WildSpawnType.bossKojaniy, PersonalityType.Vigilante },
            { WildSpawnType.followerKojaniy, PersonalityType.Stalker },
            { WildSpawnType.bossZryachiy, PersonalityType.Strategic },
            { WildSpawnType.followerZryachiy, PersonalityType.Cautious }
        };

        private static readonly BotPersonalityProfile _nullProfileFallback = BotPersonalityPresets.GenerateProfile(PersonalityType.Balanced);
        private static readonly AIRefactoredBotOwner _nullOwnerFallback = new AIRefactoredBotOwner();
        private static readonly BotComponentCache _nullCacheFallback = new BotComponentCache();

        private static bool _debug = true;
        private static ManualLogSource Logger => Plugin.LoggerInstance;

        #endregion

        #region Public API

        public static void Clear()
        {
            _profileRegistry.Clear();
            _ownerRegistry.Clear();
            _fallbackProfiles.Clear();
            _missingLogged.Clear();

            if (_debug)
            {
                Logger.LogDebug("[BotRegistry] Cleared all bot personality and owner data.");
            }
        }

        public static void EnableDebug(bool enable)
        {
            _debug = enable && !FikaHeadlessDetector.IsHeadless;

            if (_debug)
            {
                Logger.LogDebug("[BotRegistry] Debug mode enabled.");
            }
        }

        public static bool Exists(string profileId)
        {
            return !string.IsNullOrEmpty(profileId) && _profileRegistry.ContainsKey(profileId);
        }

        public static BotPersonalityProfile Get(string profileId, PersonalityType fallback = PersonalityType.Balanced)
        {
            if (string.IsNullOrEmpty(profileId))
            {
                if (_debug)
                {
                    Logger.LogWarning("[BotRegistry] Requested null or empty profileId. Using fallback.");
                }
                return GetFallbackProfile(fallback);
            }

            if (_profileRegistry.TryGetValue(profileId, out var profile))
            {
                return profile;
            }

            if (_debug && _missingLogged.Add(profileId))
            {
                Logger.LogWarning("[BotRegistry] Missing profile for '" + profileId + "'. Using fallback: " + fallback + ".");
            }
            return GetFallbackProfile(fallback);
        }

        public static BotPersonalityProfile GetOrRegister(BotOwner bot)
        {
            if (bot == null || bot.Profile == null || bot.Profile.Info == null)
            {
                return _nullProfileFallback;
            }

            string profileId = bot.Profile.Id;
            if (_profileRegistry.TryGetValue(profileId, out var profile))
            {
                return profile;
            }

            WildSpawnType role = bot.Profile.Info.Settings?.Role ?? WildSpawnType.assault;
            PersonalityType type = _roleMap.TryGetValue(role, out var mapped) ? mapped : PersonalityType.Balanced;

            profile = BotPersonalityPresets.GenerateProfile(type);
            _profileRegistry[profileId] = profile;

            if (_debug)
            {
                Logger.LogDebug("[BotRegistry] Registered '" + type + "' for role '" + role + "' (" + profileId + ").");
            }
            return profile;
        }

        public static BotPersonalityProfile GetOrGenerate(string profileId, PersonalityType defaultType)
        {
            if (string.IsNullOrEmpty(profileId))
            {
                if (_debug)
                {
                    Logger.LogWarning("[BotRegistry] GetOrGenerate failed — null or empty profileId.");
                }
                return GetFallbackProfile(defaultType);
            }

            if (_profileRegistry.TryGetValue(profileId, out var profile))
            {
                return profile;
            }

            profile = BotPersonalityPresets.GenerateProfile(defaultType);
            _profileRegistry[profileId] = profile;

            if (_debug)
            {
                Logger.LogDebug("[BotRegistry] Auto-generated profile for '" + profileId + "' with type: " + defaultType);
            }
            return profile;
        }

        public static BotPersonalityProfile GetOrGenerate(string profileId, PersonalityType defaultType, WildSpawnType role)
        {
            if (string.IsNullOrEmpty(profileId))
            {
                var resolved = _roleMap.TryGetValue(role, out var alt) ? alt : defaultType;
                if (_debug)
                {
                    Logger.LogWarning("[BotRegistry] Null profileId. Fallback resolved to: " + resolved);
                }
                return GetFallbackProfile(resolved);
            }

            if (_profileRegistry.TryGetValue(profileId, out var profile))
            {
                return profile;
            }

            var type = _roleMap.TryGetValue(role, out var mapped) ? mapped : defaultType;
            profile = BotPersonalityPresets.GenerateProfile(type);
            _profileRegistry[profileId] = profile;

            if (_debug)
            {
                Logger.LogDebug("[BotRegistry] Auto-generated profile for '" + profileId + "' with type: " + type + " (role: " + role + ")");
            }
            return profile;
        }

        public static void Register(string profileId, BotPersonalityProfile profile)
        {
            if (!string.IsNullOrEmpty(profileId) && profile != null && !_profileRegistry.ContainsKey(profileId))
            {
                _profileRegistry[profileId] = profile;

                if (_debug)
                {
                    Logger.LogDebug("[BotRegistry] Registered personality profile for '" + profileId + "': " + profile.Personality);
                }
            }
        }

        /// <summary>
        /// Atomically registers the owner ONLY if the cache exists and is fully wired, otherwise abort and retry later.
        /// </summary>
        public static void RegisterOwner(string profileId, AIRefactoredBotOwner owner)
        {
            if (string.IsNullOrEmpty(profileId) || owner == null)
                return;

            if (!_ownerRegistry.TryGetValue(profileId, out var existing))
            {
                // Atomic: Only register owner if cache is present and owner.Cache is valid.
                if (owner.Cache == null)
                {
                    if (_debug)
                        Logger.LogWarning("[BotRegistry] Cannot register owner for '" + profileId + "' — missing BotComponentCache. Will retry.");
                    return; // Abort. BotComponentCacheRegistry must trigger owner registration once cache exists.
                }
                _ownerRegistry[profileId] = owner;
                if (_debug)
                    Logger.LogDebug("[BotRegistry] Registered AIRefactoredBotOwner for '" + profileId + "'.");
                return;
            }
            // Already exists; only update if not the same object
            if (!ReferenceEquals(existing, owner))
            {
                if (_debug)
                    Logger.LogWarning("[BotRegistry] Duplicate owner detected for '" + profileId + "'. Forcing atomic rewire.");
                // Rewire the registry to always point to the correct owner with valid cache
                if (owner.Cache != null)
                {
                    _ownerRegistry[profileId] = owner;
                    if (_debug)
                        Logger.LogDebug("[BotRegistry] Overwrote owner for '" + profileId + "' with valid owner+cache.");
                }
                else
                {
                    if (_debug)
                        Logger.LogWarning("[BotRegistry] Owner duplicate has missing cache for '" + profileId + "'. Skipping rewire, will retry.");
                }
            }
        }

        public static bool TryGet(string profileId, out BotPersonalityProfile profile)
        {
            if (!string.IsNullOrEmpty(profileId) && _profileRegistry.TryGetValue(profileId, out profile))
                return true;

            profile = _nullProfileFallback;
            return false;
        }

        public static bool TryGetRefactoredOwner(string profileId, out AIRefactoredBotOwner owner)
        {
            if (!string.IsNullOrEmpty(profileId) && _ownerRegistry.TryGetValue(profileId, out owner) && owner != null)
                return true;

            owner = _nullOwnerFallback;
            return false;
        }

        public static bool TryGetCache(string profileId, out BotComponentCache cache)
        {
            if (!string.IsNullOrEmpty(profileId) &&
                _ownerRegistry.TryGetValue(profileId, out var owner) &&
                owner != null &&
                owner.Cache != null)
            {
                cache = owner.Cache;
                return true;
            }

            cache = _nullCacheFallback;
            return false;
        }

        public static bool HasCache(string profileId)
        {
            return !string.IsNullOrEmpty(profileId)
                && _ownerRegistry.TryGetValue(profileId, out var owner)
                && owner != null
                && owner.Cache != null;
        }

        #endregion

        #region Internals

        private static BotPersonalityProfile GetFallbackProfile(PersonalityType fallback)
        {
            if (_fallbackProfiles.TryGetValue(fallback, out var cached))
                return cached;

            var profile = BotPersonalityPresets.GenerateProfile(fallback);
            _fallbackProfiles[fallback] = profile;

            if (_debug)
            {
                Logger.LogDebug("[BotRegistry] Created fallback personality: " + profile.Personality);
            }
            return profile;
        }

        #endregion
    }
}
