// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Failures in AIRefactored logic must always trigger safe fallback to EFT base AI.
// </auto-generated>

namespace AIRefactored.AI.Groups
{
    using System.Collections.Generic;
    using AIRefactored.AI.Missions;
    using AIRefactored.Core;
    using EFT;
    using UnityEngine;

    /// <summary>
    /// Assigns and caches squad mission types per GroupId for squad-coordinated routing and objectives.
    /// Dynamically weighted based on map type, squad composition, and bot personality.
    /// </summary>
    public static class GroupMissionCoordinator
    {
        #region Static State

        private static readonly Dictionary<string, BotMissionController.MissionType> AssignedMissions =
            new Dictionary<string, BotMissionController.MissionType>(32);

        #endregion

        #region Public API

        public static void ForceMissionForGroup(string groupId, BotMissionController.MissionType mission)
        {
            if (!string.IsNullOrEmpty(groupId))
            {
                AssignedMissions[groupId] = mission;
            }
        }

        public static BotMissionController.MissionType GetMissionForGroup(BotOwner bot)
        {
            if (!EFTPlayerUtil.IsValidBotOwner(bot))
            {
                return BotMissionController.MissionType.Loot;
            }

            Player player = bot.GetPlayer;
            Profile profile = player?.Profile;
            string groupId = profile?.Info?.GroupId;

            if (string.IsNullOrEmpty(groupId))
            {
                return PickMission(bot);
            }

            if (!AssignedMissions.TryGetValue(groupId, out BotMissionController.MissionType result))
            {
                result = PickMission(bot);
                AssignedMissions[groupId] = result;
            }

            return result;
        }

        public static void RegisterFromBot(BotOwner bot)
        {
            if (!EFTPlayerUtil.IsValidBotOwner(bot))
            {
                return;
            }

            Player player = bot.GetPlayer;
            Profile profile = player?.Profile;
            string groupId = profile?.Info?.GroupId;

            if (!string.IsNullOrEmpty(groupId) && !AssignedMissions.ContainsKey(groupId))
            {
                AssignedMissions[groupId] = PickMission(bot);
            }
        }

        public static void Reset()
        {
            AssignedMissions.Clear();
        }

        #endregion

        #region Mission Picker

        private static BotMissionController.MissionType PickMission(BotOwner bot)
        {
            float loot = 1f;
            float fight = 1f;
            float quest = 1f;

            string map = GameWorldHandler.TryGetValidMapName();
            switch (map)
            {
                case "factory4_day":
                case "factory4_night":
                    fight += 1.5f;
                    break;
                case "woods":
                    loot += 1.5f;
                    break;
                case "bigmap":
                    quest += 0.75f;
                    fight += 0.25f;
                    break;
                case "interchange":
                    loot += 1.2f;
                    break;
                case "rezervbase":
                    fight += 1.0f;
                    loot += 0.4f;
                    break;
                case "lighthouse":
                    quest += 1.2f;
                    loot += 1.0f;
                    break;
                case "shoreline":
                    quest += 1.4f;
                    loot += 0.6f;
                    break;
                case "tarkovstreets":
                    fight += 1.3f;
                    loot += 0.5f;
                    break;
                case "laboratory":
                    fight += 2.0f;
                    break;
                case "sandbox":
                case "sandbox_high":
                case "groundzero":
                    loot += 1.0f;
                    break;
                default:
                    loot += 0.5f;
                    break;
            }

            if (BotRegistry.TryGet(bot.ProfileId, out BotPersonalityProfile personality))
            {
                loot += personality.Caution;
                quest += personality.Caution * 0.5f;
                fight += personality.AggressionLevel * 1.2f;

                if (personality.IsFrenzied)
                {
                    fight += 1.5f;
                }

                if (personality.IsFearful)
                {
                    loot += 1.0f;
                }

                if (personality.IsCamper)
                {
                    quest += 0.75f;
                }
            }

            float total = loot + fight + quest;
            float roll = Random.value * total;

            if (roll < loot)
            {
                return BotMissionController.MissionType.Loot;
            }

            if (roll < loot + fight)
            {
                return BotMissionController.MissionType.Fight;
            }

            return BotMissionController.MissionType.Quest;
        }

        #endregion
    }
}
