// <auto-generated>
//   This file is part of AI-Refactored, an open-source project focused on realistic AI behavior in Escape from Tarkov.
//   Licensed under the MIT License. See LICENSE in the repository root for more information.
//
//   THIS FILE IS SYSTEMATICALLY MANAGED.
//   Please follow strict StyleCop, ReSharper, and AI-Refactored code standards for all modifications.
// </auto-generated>

namespace AIRefactored.AI.Medical
{
    using System;
    using AIRefactored.AI.Core;
    using AIRefactored.Core;
    using EFT;
    using UnityEngine;

    /// <summary>
    /// Controls bot healing behavior using first aid, surgery, or stimulators.
    /// Supports healing squadmates using internal EFT BotHealAnotherTarget logic.
    /// </summary>
    public sealed class BotMedicLogic
    {
        #region Constants

        private const float HealCheckInterval = 1.5f;
        private const float HealSquadRange = 4f;

        #endregion

        #region Fields

        private readonly BotComponentCache _cache;
        private readonly BotInjurySystem _injurySystem;
        private readonly BotOwner _bot;

        private BotMedecine _med;
        private float _nextHealCheck;
        private bool _isHealing;

        #endregion

        #region Constructor

        /// <summary>
        /// Constructs the bot medic logic system.
        /// </summary>
        public BotMedicLogic(BotComponentCache cache, BotInjurySystem injurySystem)
        {
            if (cache == null)
            {
                throw new ArgumentNullException(nameof(cache));
            }

            if (injurySystem == null)
            {
                throw new ArgumentNullException(nameof(injurySystem));
            }

            if (cache.Bot == null)
            {
                throw new ArgumentException("Bot reference is null", nameof(cache));
            }

            this._cache = cache;
            this._injurySystem = injurySystem;
            this._bot = cache.Bot;
            this._nextHealCheck = Time.time;

            if (this._bot.HealAnotherTarget == null)
            {
                this._bot.HealAnotherTarget = new BotHealAnotherTarget(this._bot);
                this._bot.HealAnotherTarget.OnHealAsked += this.OnHealAsked;
            }

            if (this._bot.HealingBySomebody == null)
            {
                this._bot.HealingBySomebody = new BotHealingBySomebody(this._bot);
            }

            this._med = this._bot.Medecine ?? new BotMedecine(this._bot);
        }

        #endregion

        #region Public API

        /// <summary>
        /// Resets medic and injury state.
        /// </summary>
        public void Reset()
        {
            this._isHealing = false;
            this._injurySystem.Reset();
            this.UnsubscribeFromFirstAid();
        }

        /// <summary>
        /// Ticks healing logic, including squad and self checks.
        /// </summary>
        public void Tick(float time)
        {
            if (this._isHealing || time < this._nextHealCheck)
            {
                return;
            }

            if (this._bot.IsDead || this._bot.GetPlayer == null || !this._bot.GetPlayer.IsAI)
            {
                return;
            }

            if (this._cache.PanicHandler != null && this._cache.PanicHandler.IsPanicking)
            {
                return;
            }

            if (this._bot.HealAnotherTarget != null && this._bot.HealAnotherTarget.IsInProcess)
            {
                return;
            }

            this._nextHealCheck = time + HealCheckInterval;

            this._injurySystem.Tick(time);

            if (this.TryHealSquadmate())
            {
                return;
            }

            this.TrySelfHeal();
        }

        #endregion

        #region Healing Logic

        private bool TryHealSquadmate()
        {
            if (this._bot.BotsGroup == null)
            {
                return false;
            }

            Player self = EFTPlayerUtil.ResolvePlayer(this._bot);
            if (!EFTPlayerUtil.IsValidGroupPlayer(self))
            {
                return false;
            }

            Vector3 selfPos = EFTPlayerUtil.GetPosition(self);
            int count = this._bot.BotsGroup.MembersCount;

            for (int i = 0; i < count; i++)
            {
                BotOwner mate = this._bot.BotsGroup.Member(i);
                if (mate == null || mate == this._bot || mate.IsDead)
                {
                    continue;
                }

                Player target = EFTPlayerUtil.ResolvePlayer(mate);
                if (!EFTPlayerUtil.IsValidGroupPlayer(target))
                {
                    continue;
                }

                Vector3 targetPos = EFTPlayerUtil.GetPosition(target);
                if ((targetPos - selfPos).sqrMagnitude > HealSquadRange * HealSquadRange)
                {
                    continue;
                }

                IPlayer iTarget = EFTPlayerUtil.AsSafeIPlayer(target);
                if (iTarget != null)
                {
                    this._bot.HealAnotherTarget.HealAsk(iTarget);
                    return true;
                }
            }

            return false;
        }

        private void TrySelfHeal()
        {
            BotFirstAidClass firstAid = this._med.FirstAid as BotFirstAidClass;
            GClass473 surgery = this._med.SurgicalKit as GClass473;
            GClass475 stim = this._med.Stimulators as GClass475;

            if (firstAid != null && firstAid.ShallStartUse())
            {
                this._isHealing = true;
                this.TrySay(EPhraseTrigger.StartHeal);
                firstAid.OnEndApply += this.OnHealComplete;
                firstAid.TryApplyToCurrentPart();
                return;
            }

            if (surgery != null && surgery.ShallStartUse())
            {
                this._isHealing = true;
                this.TrySay(EPhraseTrigger.StartHeal);
                surgery.ApplyToCurrentPart();
                return;
            }

            if (stim != null && stim.CanUseNow())
            {
                this._isHealing = true;
                stim.StartApplyToTarget(this.OnStimComplete);
            }
        }

        #endregion

        #region Callbacks

        private void OnHealAsked(IPlayer target)
        {
            this._isHealing = true;
            this.TrySay(EPhraseTrigger.StartHeal);
        }

        private void OnHealComplete(BotOwner _)
        {
            this._isHealing = false;
            this._injurySystem.Reset();
            this.UnsubscribeFromFirstAid();
        }

        private void OnSurgeryComplete(bool success)
        {
            this._isHealing = false;
            BotFirstAidClass fa = this._med.FirstAid as BotFirstAidClass;
            if (fa != null)
            {
                fa.CheckParts();
            }
        }

        private void OnStimComplete(bool success)
        {
            this._isHealing = false;
        }

        private void TrySay(EPhraseTrigger trigger)
        {
            if (!FikaHeadlessDetector.IsHeadless && this._bot.BotTalk != null)
            {
                this._bot.BotTalk.TrySay(trigger);
            }
        }

        private void UnsubscribeFromFirstAid()
        {
            BotFirstAidClass fa = this._med.FirstAid as BotFirstAidClass;
            if (fa != null)
            {
                fa.OnEndApply -= this.OnHealComplete;
            }
        }

        #endregion
    }
}
